# FROM node:19.1.0

# RUN mkdir -p /app

# WORKDIR /app

# COPY ./package*.json .

# RUN npm install 
# RUN npm install create-react-app 
# RUN npm install react-scripts 
# RUN npm install react-router-dom

# COPY ./ .

# #RUN npm run build
# CMD [ "npm", "start" ]